### ISSUE TITLE
[Question] Autocompletion?

### ISSUE THREAD

**Issue by Batres3** [Majixed/vim-dotfiles#1]
As the title suggests, I’m looking to see if there’s any way to enable autocompletion in Vim, since, as far as I know, we can’t install cmake or Neovim on a-shell

**Comment by Majixed** [comment]
Sorry for the extremely late response! I haven't been keeping up with my repos lately. I believe autocompletion for vim isn't currently possible in a-Shell, so trying to use plugins like jedi will actually cause the app to crash. And yes, installing cmake or nvim isn't possible either due to Apple's restrictions.
